### ISSUE TITLE
Non SASL auth

### ISSUE THREAD

**Issue by lopcode** [voxelcarrot/Warren#3]
Probably requires more generalised notion of auth with different things that can fulfil it, and try them in order (SASL then NickServ by default, for example).

Must be able to defer joining channels until auth has completed. There's apparently a numeric response to needing to be identified to join a channel as well.

**Comment by nomis** [comment]
There's a numeric for needing to be identified to join a channel, I'd normally script that to automatically authenticate and retry (if services are not available).

There are also at least four different ways to identify after connecting:
- "PRIVMSG servicename :identify [nickname] password"
- "PRIVMSG servicename@servername :identify [nickname] password"
- "NICKSERV :identify [nickname] password"
- "IDENTIFY :[nickname] password"

Sometimes it's "AuthServ" instead of "NickServ" or "auth" intsead of "identify".
GameSurge and QuakeNet are good examples of alternative services/commands.

**Comment by lopcode** [comment]
Thanks, that pretty much confirms my suspicions about it needing to be a more generic "auth" system.

**Comment by lopcode** [comment]
Is there a common way to discover services and their capabilities? Or is it enough to let the user choose the name of the service? Is there a check that can be done to see if NickServ is indeed the right service, and not someone masquerading as it?

**Comment by DanielOaks** [comment]
Using the `NICKSERV` or `IDENTIFY` commands directly will pretty much make sure someone isn't masquerading as it. If those aliases aren't setup though, not too much of a way for you to tell.

The normal way I've seen to implement this is just to have a dropdown list to let the user select from a few options of how to auth (sasl PLAIN, sasl EXTERNAL, NICKSERV, IDENTIFY, privmsg etc).

The good thing about SASL is that if you do it on connection, you can just wait 'til you receive the 001/MOTD numerics to send channel joins. If you're doing it this way, really the easiest thing to do is just wait a configurable amount of time after receiving 001/MOTD numerics before sending the joins (usually a couple seconds or so).

**Comment by lopcode** [comment]
Yeah, SASL auth is done during registration, so I didn't have any of these headaches. I've done it with a pause in the past but that feels a bit gross. I didn't even know about the aliased commands, so I'll look in to their support, thanks!

**Comment by DanielOaks** [comment]
Coolcool, most of the bigger IRCds implement them, but whether they return those fancy new numerics or not is basically up in the air as they're nonstandard, so try not to rely on the numerics returning for those :)

**Comment by lopcode** [comment]
Done in 4ef6a39728e8570d24f85542b8c2a829af9a84a8. Uses "NICKSERV" command as it seems pretty ubiquitous (all the networks I'm connected to support it, at least). Doesn't bother trying to parse replies, just assumes it succeeds. If authing with nickserv waits 5 seconds by default and then joins channels after an MOTD. Prints out a warning to use SASL if possible.
